apiVersion: v2
name: zfs-localpv
description: CSI Driver for dynamic provisioning of ZFS Persistent Local Volumes.
version: 1.6.4
appVersion: 1.6.0
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
home: http://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - filesystem
  - ZFS
  - Local Persistent Volumes
  - storage
sources:
- https://github.com/openebs/zfs-localpv
maintainers:
  - name: xUnholy
    email: michaelfornaro@gmail.com
  - name: prateekpandey14
    email: prateek.pandey@mayadata.io
  - name: pawanpraka1
    email: pawan@mayadata.io
